-- Supabase SQL Editorで実行してください。

-- スニペットテーブルの作成
CREATE TABLE IF NOT EXISTS snippets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  tags TEXT,
  html_code TEXT,
  css_code TEXT,
  js_code TEXT,
  screenshot_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- インデックスの作成
CREATE INDEX IF NOT EXISTS idx_snippets_category ON snippets(category);
CREATE INDEX IF NOT EXISTS idx_snippets_title ON snippets(title);

-- ストレージバケットの作成（SQL Editorで実行するか、管理画面の Storage > New Bucket から作成してください）
-- GUIの管理画面から "snippets" という名前のPublicバケットを作成するのが最も簡単です。
INSERT INTO storage.buckets (id, name, public) VALUES ('snippets', 'snippets', true)
ON CONFLICT (id) DO NOTHING;

-- 画像へのパブリックアクセスを許可するポリシー（GUIの Storage > snippets > Policies からも設定可能）
CREATE POLICY "Public Access" ON storage.objects FOR SELECT TO public USING ( bucket_id = 'snippets' );
CREATE POLICY "Auth Upload" ON storage.objects FOR INSERT TO anon WITH CHECK ( bucket_id = 'snippets' );
